# Generated by Django 5.0.4 on 2024-05-15 23:44

from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=deletion.CASCADE, to='auth.user')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
