# Generated by Django 5.0.4 on 2024-06-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_companylocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('tax', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
