# Generated by Django 5.0.4 on 2024-06-30 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('size_quantity_per_carton', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('user', models.CharField(max_length=100)),
                ('barcodeValue', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companylocation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
            ],
        ),
    ]
