# Generated by Django 5.0.4 on 2024-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_productdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
