# Generated by Django 5.0.4 on 2024-06-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_productdata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='barcode_value',
            new_name='barcodeValue',
        ),
    ]
